from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = PROJECT_ROOT / "examples"
BUILD_DIR = PROJECT_ROOT / "build"

SUPERSCALAR = False

DATA_MEMORY_SIZE = 2**12

TMP_BASE = 0

PTR_TMP = 200
XTR_TMP = 201
ZERO_CELL = 202
DATA_BASE = 203

STACK_TOP = 4095

START_IP = 1
IRQ_VECTOR_ADDR = 0

START_TICK = 400
TICK_INTERVAL = 400

MAX_TICKS = 1_000_000
